### ISSUE TITLE
no zhuangbi we are still friends

### ISSUE THREAD

**Issue by TinChak** [yangboz/crispy-octo-moo#3]
不装逼咱还是好朋友~~堂堂炎黄子孙，怎么全是英文

**Comment by yangboz** [comment]
想参与吗？

**Comment by TinChak** [comment]
哈哈，当然想了。看好Meteor与ionic结合开发应用，但不想用官方的那个。想用angular-meteor与ionic结合。。您的项目中怎么看不到meteor的影子呢？

**Comment by yangboz** [comment]
对不起，你连影子都找不到，谢绝参观！

**Comment by TinChak** [comment]
确实没看到。。明明就只有ionic啊~~
